name: lint and deploy site
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node--
    - name: build & test
      run: |
        npm install
        npm run build
        npm run export
        touch out/.nojekyll # https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
    - name: deploy the site
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        build_dir: out
        fqdn: ${{ secrets.SITE_FQDN }}
      env:
        GITHUB_PAT: ${{ secrets.DEPLOYMENT_PAT }}
