name: lint and deploy site
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: build and test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake ci:lint
    - name: deploy the site
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        build_dir: docs
        fqdn: ${{ secrets.SITE_FQDN }}
      env:
        GITHUB_PAT: ${{ secrets.DEPLOYMENT_PAT }}
